In [1]:
#pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
#built on top of the Python programming language. 

#2008 by mckinney
#very useful with structured data(tabular data)

In [3]:
import pandas as pd

In [ ]:
#pd.read_csv() #Read a comma-separated values(csv) file into DataFrame.

In [5]:
df = pd.read_csv("services.csv")

In [7]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [9]:
#by default pandas understands the first row as the column name

In [11]:
#when you don't want pandas to consider first row as column name
pd.read_csv("services.csv", header = None) #internal integer indexes are provided by pandas for both rows and columns

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [13]:
pd.read_csv("services.csv", skiprows=2) #skip first two rows while reading the data

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [15]:
pd.read_csv("services.csv", usecols=["program_id", "application_process"])

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [17]:
df = pd.read_csv("services.csv")

In [19]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [21]:
#data structure >> series and dataframe
#series >> 1 dimensional in nature
#dataframe >> 2 dimensional in nature, multiple series combine to form a dataframe

In [23]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [25]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df.application_process

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: object

In [29]:
df["application_process"]

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: object

In [31]:
type(df["application_process"]) #a column is a series in a dataframe

pandas.core.series.Series

In [33]:
l = [1, 2, 3, 4]
pd.Series(l)

0    1
1    2
2    3
3    4
dtype: int64

In [35]:
l = [1, 2, 3, 4]
s = pd.Series(l)

In [37]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [39]:
s[0]

1

In [41]:
s[1:]

1    2
2    3
3    4
dtype: int64

In [43]:
s[2:4]

2    3
3    4
dtype: int64

In [45]:
#by default indexes are integer, we can have custom indexes

pd.Series([100, 200, 300], index = ["Ajay", "Bijay", 1])

Ajay     100
Bijay    200
1        300
dtype: int64

In [47]:
d = pd.Series([100, 200, 300], index = ["Ajay", "Bijay", 1])

In [49]:
d

Ajay     100
Bijay    200
1        300
dtype: int64

In [51]:
type(d)

pandas.core.series.Series

In [53]:
d["Ajay"]

100

In [55]:
#to see all the index of a series 
d.index

Index(['Ajay', 'Bijay', 1], dtype='object')

In [57]:
#to reset index
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [59]:
pd.DataFrame(d)

         0
Ajay   100
Bijay  200
1      300

In [61]:
df.head(2) #first two rows

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [209]:
df.tail(2) #last two rows

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [65]:
df.shape #23 rows are there and #22 columns are there

(23, 22)

In [67]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [69]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [71]:
df.sample() #gives a random row

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN

In [73]:
df.sample(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      object
 4   alternate_name           1 non-null      object
 5   application_process      23 non-null     object
 6   audience                 14 non-null     object
 7   description              23 non-null     object
 8   eligibility              17 non-null     object
 9   email                    1 non-null      object
 10  fees                     21 non-null     object
 11  funding_sources          21 non-null     object
 12  interpretation_services  1 non-null      object
 13  keywords                 21 non-null     object
 14  languages                1 non-null      object
 15  name                     23 non-null     object
 16  required_documents       1 non-null      object
 17  service_areas            21 non-null     object
 18  status                   23 non-null     object
 19  wait_time                19 non-null     object
 20  website                  2 non-null      object
 21  taxonomy_ids             1 non-null      object
dtypes: float64(1), int64(2), object(19)
memory usage: 4.1+ KB

In [77]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [79]:
df['id']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [81]:
df['fees']

0     $2.50 suggested donation for lunch for age 60 ...
1     None. Donations requested of clients who can a...
2                                                 None.
3     Vary according to income ($5-$90). Cash, check...
4         $60 application fee. Cash or checks accepted.
5     $55 per year membership dues. Classes have fee...
6     $85 per day. Vary according to income for thos...
7     Suggested donation of $4.25 per meal for senio...
8                                                 None.
9                                                 None.
10                                                None.
11                                                None.
12                                                None.
13                                                None.
14                                                None.
15    None for emergency services. Vary for after sc...
16                                                None.
17                                                None.
18                                                None.
19                                                  NaN
20                                                  NaN
21    None, except for permits and photocopying. Cas...
22    None, except for permits and photocopying. Cas...
Name: fees, dtype: object

In [83]:
df['application_process']

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: object

In [85]:
type(df['application_process'])

pandas.core.series.Series

In [87]:
#series to dataframe
s = pd.Series([2, 3, 4], index = [100, "Ajay", 200])
s

100     2
Ajay    3
200     4
dtype: int64

In [89]:
d = pd.DataFrame(s)

In [91]:
d

      0
100   2
Ajay  3
200   4

In [93]:
type(d)

pandas.core.frame.DataFrame

In [95]:
d["new column"] = "Chandan"

In [97]:
d

      0 new column
100   2    Chandan
Ajay  3    Chandan
200   4    Chandan

In [99]:
d["new column"] #best way to access the column this way but if it is a continuous string, you can access using df.column

100     Chandan
Ajay    Chandan
200     Chandan
Name: new column, dtype: object

In [101]:
d.new column #it is continuous thats why it will throw an error

SyntaxError: invalid syntax (4053788551.py, line 1)

In [103]:
d

      0 new column
100   2    Chandan
Ajay  3    Chandan
200   4    Chandan

In [105]:
d["new_column2"] = [1, 2, 3] #no of new column elements should be equal to no of rows

In [107]:
d

      0 new column  new_column2
100   2    Chandan            1
Ajay  3    Chandan            2
200   4    Chandan            3

In [109]:
#to get columns name

In [111]:
d.columns

Index([0, 'new column', 'new_column2'], dtype='object')

In [113]:
#to change column names

In [115]:
d.columns = ["col1", "col2", "col3"]

In [117]:
d

      col1     col2  col3
100      2  Chandan     1
Ajay     3  Chandan     2
200      4  Chandan     3

In [119]:
#reset index
d.reset_index()

  index  col1     col2  col3
0   100     2  Chandan     1
1  Ajay     3  Chandan     2
2   200     4  Chandan     3

In [121]:
#if you don't want the original index to be a column name
d.reset_index(drop=True)

   col1     col2  col3
0     2  Chandan     1
1     3  Chandan     2
2     4  Chandan     3

In [123]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [125]:
#accessing one column
df["status"]

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: object

In [127]:
#accessing two or more columns
df[["status", "languages"]]

      status languages
0     active       NaN
1     active       NaN
2     active       NaN
3     active       NaN
4     active       NaN
5     active       NaN
6     active       NaN
7     active       NaN
8     active       NaN
9     active       NaN
10    active       NaN
11    active       NaN
12    active       NaN
13    active       NaN
14    active       NaN
15    active       NaN
16    active       NaN
17    active       NaN
18    active       NaN
19   defunct       NaN
20  inactive       NaN
21    active   Spanish
22    active       NaN

In [129]:
df[["name", "status", "languages"]]

                                    name    status languages
0        Fair Oaks Adult Activity Center    active       NaN
1       Second Career Employment Program    active       NaN
2                 Senior Peer Counseling    active       NaN
3               Family Visitation Center    active       NaN
4      Economic Self-Sufficiency Program    active       NaN
5   Little House Recreational Activities    active       NaN
6       Rosener House Adult Day Services    active       NaN
7         Meals on Wheels - South County    active       NaN
8                       Fair Oaks Branch    active       NaN
9                           Main Library    active       NaN
10                       Schaberg Branch    active       NaN
11                          Project Read    active       NaN
12                 Redwood Shores Branch    active       NaN
13                    Redwood City Corps    active       NaN
14           Adult Rehabilitation Center    active       NaN
15                       Sunnyvale Corps    active       NaN
16     South San Francisco Citadel Corps    active       NaN
17                         Project Smile    active       NaN
18         San Mateo Free Medical Clinic    active       NaN
19             Service with blank fields   defunct       NaN
20       Service for Admin Test Location  inactive       NaN
21                       Passport Photos    active   Spanish
22                  Example Service Name    active       NaN

In [131]:
#accessing one column--series, multiple columns(with square bracket becomes a dataframe)
df_subset = df[["name", "status", "languages"]]

In [133]:
df_subset

                                    name    status languages
0        Fair Oaks Adult Activity Center    active       NaN
1       Second Career Employment Program    active       NaN
2                 Senior Peer Counseling    active       NaN
3               Family Visitation Center    active       NaN
4      Economic Self-Sufficiency Program    active       NaN
5   Little House Recreational Activities    active       NaN
6       Rosener House Adult Day Services    active       NaN
7         Meals on Wheels - South County    active       NaN
8                       Fair Oaks Branch    active       NaN
9                           Main Library    active       NaN
10                       Schaberg Branch    active       NaN
11                          Project Read    active       NaN
12                 Redwood Shores Branch    active       NaN
13                    Redwood City Corps    active       NaN
14           Adult Rehabilitation Center    active       NaN
15                       Sunnyvale Corps    active       NaN
16     South San Francisco Citadel Corps    active       NaN
17                         Project Smile    active       NaN
18         San Mateo Free Medical Clinic    active       NaN
19             Service with blank fields   defunct       NaN
20       Service for Admin Test Location  inactive       NaN
21                       Passport Photos    active   Spanish
22                  Example Service Name    active       NaN

In [135]:
type(df_subset)

pandas.core.frame.DataFrame

In [137]:
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [138]:
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [141]:
df1.shape

(28, 10)

In [143]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      object
 4   alternate_name           1 non-null      object
 5   application_process      23 non-null     object
 6   audience                 14 non-null     object
 7   description              23 non-null     object
 8   eligibility              17 non-null     object
 9   email                    1 non-null      object
 10  fees                     21 non-null     object
 11  funding_sources          21 non-null     object
 12  interpretation_services  1 non-null      object
 13  keywords                 21 non-null     object
 14  languages                1 non-null      object
 15  name                     23 non-null     object
 16  required_documents       1 non-null      object
 17  service_areas            21 non-null     object
 18  status                   23 non-null     object
 19  wait_time                19 non-null     object
 20  website                  2 non-null      object
 21  taxonomy_ids             1 non-null      object
dtypes: float64(1), int64(2), object(19)
memory usage: 4.1+ KB

In [147]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [149]:
pd.read_csv("taxonomy.csv")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [151]:
df3 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [152]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [155]:
df3.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [157]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [159]:
df3.shape

(891, 12)

In [161]:
df3.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [163]:
df3.Sex  #one way

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [165]:
df3["Sex"] #another way

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [167]:
df3.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [169]:
df3[["PassengerId", "Sex", "Name"]]  #subset of data

     PassengerId     Sex                                               Name
0              1    male                            Braund, Mr. Owen Harris
1              2  female  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3  female                             Heikkinen, Miss. Laina
3              4  female       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5    male                           Allen, Mr. William Henry
..           ...     ...                                                ...
886          887    male                              Montvila, Rev. Juozas
887          888  female                       Graham, Miss. Margaret Edith
888          889  female           Johnston, Miss. Catherine Helen "Carrie"
889          890    male                              Behr, Mr. Karl Howell
890          891    male                                Dooley, Mr. Patrick

[891 rows x 3 columns]

In [171]:
#reading data from an HTLML page

In [173]:
pip install lxml

Requirement already satisfied: lxml in c:\users\chandan singh\anaconda3\lib\site-packages (5.2.1)
Note: you may need to restart the kernel to use updated packages.

In [174]:
url_df = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [175]:
type(url_df)

list

In [176]:
url_df[0]

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
df4 = url_df[0]

In [183]:
df4

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
df4.shape

(652, 32)

In [187]:
df4.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [189]:
df4.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [191]:
df4.info() #to get the data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 32 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       651 non-null    float64
 1   Player   652 non-null    object
 2   Age      651 non-null    float64
 3   Team     651 non-null    object
 4   Pos      651 non-null    object
 5   G        651 non-null    float64
 6   GS       651 non-null    float64
 7   MP       651 non-null    float64
 8   FG       651 non-null    float64
 9   FGA      651 non-null    float64
 10  FG%      650 non-null    float64
 11  3P       651 non-null    float64
 12  3PA      651 non-null    float64
 13  3P%      571 non-null    float64
 14  2P       651 non-null    float64
 15  2PA      651 non-null    float64
 16  2P%      648 non-null    float64
 17  eFG%     650 non-null    float64
 18  FT       651 non-null    float64
 19  FTA      651 non-null    float64
 20  FT%      627 non-null    float64
 21  ORB      651 non-null    float64
 22  DRB      651 non-null    float64
 23  TRB      651 non-null    float64
 24  AST      651 non-null    float64
 25  STL      651 non-null    float64
 26  BLK      651 non-null    float64
 27  TOV      651 non-null    float64
 28  PF       651 non-null    float64
 29  PTS      651 non-null    float64
 30  Trp-Dbl  651 non-null    float64
 31  Awards   60 non-null     object
dtypes: float64(28), object(4)
memory usage: 163.1+ KB

In [193]:
df4.dtypes #to get only data types

Rk         float64
Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Trp-Dbl    float64
Awards      object
dtype: object

In [195]:
#to save the above file in your local

In [197]:
df4  #it has default index

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [199]:
df4.to_csv("player.csv") #write object to a comma-separated values(csv) file

In [201]:
df4.to_csv("players.csv", index=False)
#to not get the index of df, pass index=False

In [203]:
#read a json file from url
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
pd.read_json(url)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,author_association,active_lock_reason,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60695,2782094308,I_kwDOAA0YD86l02Pk,60695,BUG: Series constructor from dictionary drops ...,...,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60694,2782041015,PR_kwDOAA0YD86Hbp9k,60694,TST(string dtype): Resolve xfails in test_from...,...,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60693,2782019632,I_kwDOAA0YD86l0kAw,60693,"ENH: add `__rshift__`, `__lshift__`, `__irshif...",...,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60692,2781798209,I_kwDOAA0YD86lzt9B,60692,ENH: Make pd.Timestamp.astimezone() default to...,...,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60690,2778992273,I_kwDOAA0YD86lpA6R,60690,ENH: frozensets are shown in parentheses (like...,...,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60686,2778058545,PR_kwDOAA0YD86HOCWT,60686,Remove editable installs from CI,...,MEMBER,NaN,The meson-python team does not suggest using e...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60685,2777461553,I_kwDOAA0YD86ljLMx,60685,ENH: Better error message for trying to conver...,...,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60684,2777093287,I_kwDOAA0YD86lhxSn,60684,BUG: Pandas to_sql 'Engine' object has no attr...,...,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60681,2776090837,PR_kwDOAA0YD86HHQPY,60681,Relax meson pins in CI,...,MEMBER,NaN,Back in https://github.com/pandas-dev/pandas/p...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60678,2775574052,I_kwDOAA0YD86lb-Yk,60678,BUG: boolean series .isin([pd.NA])] inconsiste...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60677,2775558091,I_kwDOAA0YD86lb6fL,60677,BUG: scalar out of bounds input does not raise...,...,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60676,2775492739,I_kwDOAA0YD86lbqiD,60676,ENH: Change default dtype of `str.get_dummies(...,...,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60675,2774076906,I_kwDOAA0YD86lWQ3q,60675,ENH: Support attrs in feather files,...,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60673,2773690931,I_kwDOAA0YD86lUyoz,60673,BUG: DataFrame.sort_values() by 2 columns and ...,...,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60671,2773302395,I_kwDOAA0YD86lTTx7,60671,BUG: .to_period with MonthBegin offset does no...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60668,2771540443,I_kwDOAA0YD86lMlnb,60668,ENH: Add support for executing UDF's using Bod...,...,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60667,2771524911,PR_kwDOAA0YD86G3m8m,60667,Implement String Accumulations with nanoarrow,...,MEMBER,NaN,This is an addon to the great work that @rhsha...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60666,2771303448,PR_kwDOAA0YD86G22eD,60666,Update docs for generating unoptimized debug b...,...,MEMBER,NaN,Not sure what changes were made recently to th...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60664,2770893106,I_kwDOAA0YD86lKHky,60664,BUG: Pandas resets counter when using filterwa...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60663,2769446265,PR_kwDOAA0YD86GwlyV,60663,ENH: Enable pytables to round-trip with String...,...,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60661,2769292863,PR_kwDOAA0YD86GwHmQ,60661,String dtype: disallow specifying the 'str' dt...,...,MEMBER,NaN,"The intention was for the new default `""str""` ...",NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60660,2769067824,I_kwDOAA0YD86lDJ8w,60660,ENH: Remove `mode` property from `BaseBuffer`,...,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60658,2768879042,PR_kwDOAA0YD86Gu2I7,60658,Added improvements to the cheat sheet based on...,...,NONE,NaN,- [x] closes #40680\r\n- [ ] Tests added and p...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60656,2768742624,I_kwDOAA0YD86lB6jg,60656,ENH: Add `date_format` and `date_unit` to `to_...,...,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60655,2768259713,PR_kwDOAA0YD86GstMK,60655,DEPS: Bump optional dependencies,...,MEMBER,NaN,These should have been out for at least ~1 yea...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60654,2767895468,PR_kwDOAA0YD86GreGx,60654,Replace flake8-rst with flake8-rst-docstrings,...,NONE,NaN,Fixes #46865\n\nReplace `flake8-rst` with `fla...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/60653,2767325404,PR_kwDOAA0YD86GpgwV,60653,TST (string dtype): clean-up interpolate tests,...,MEMBER,NaN,Small follow-up on https://github.com/pandas-d...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60651,2767108199,I_kwDOAA0YD86k7rhn,60651,QST:,...,NONE,NaN,### Research\n\n- [X] I have searched the [[pa...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60647,2766142492,I_kwDOAA0YD86k3_wc,60647,BUG: CustomBusinessDay not respecting calendar,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/60646,2765987527,I_kwDOAA0YD86k3Z7H,60646,BUG: max on `axis=1` returns wrong values on t...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN

In [204]:
import requests
data = requests.get(url)

In [207]:
data